updated the code of factorial and coffee shop
Tech-Training-2021/Neosoft-dotnet pull request #35
Opened 2021-08-06 06:17 UTC by harsh3294

updated the code of factorial ==> if the user adds the negative value then it wont allow and it will display the invalid input 
updated the code of coffee shop ==> added the menu , also it ask the user to add the quantity

2021-08-06 06:53 UTC, kaurrevature requested changes

2021-08-06 06:53 UTC, kaurrevature commented on 02/HelloWorld/HelloWorld.sln
> +	EndGlobalSection
@harsh3294 unstage these files and make another PR

2021-08-06 06:53 UTC, kaurrevature commented on 02/HelloWorld/HelloWorld/HelloWorld.csproj
> +    <TargetFramework>net5.0</TargetFramework>
@harsh3294  remove this file

2021-08-06 07:05 UTC, harsh3294 commented on 02/HelloWorld/HelloWorld/HelloWorld.csproj
> +    <TargetFramework>net5.0</TargetFramework>
removed file

2021-08-11 07:17 UTC, kaurrevature requested changes
There are 12 files added, only 3 files need to be committed. Please do the needful.

2021-08-11 07:17 UTC, closed without merging