Added SP
Tech-Training-2021/Neosoft-dotnet pull request #90
Opened 2021-09-01 07:11 UTC by Himani-ja

2021-09-01 07:18 UTC, kaurrevature requested changes

2021-09-01 07:18 UTC, kaurrevature commented on 05/PetStore/PetStore/Program.cs
> +             Console.Write("PLease enter the Id of the cat whose name is to be changed ");
refactor this code to a method

2021-09-01 07:18 UTC, kaurrevature commented on 05/PetStore/PetTest/PetTest.csproj
>    <PropertyGroup>
don't push this file

2021-09-01 07:24 UTC, Himani-ja commented on 05/PetStore/PetStore/Program.cs
> +             Console.Write("PLease enter the Id of the cat whose name is to be changed ");
ma'am this code is not ours

2021-09-06 07:44 UTC, closed without merging

2021-09-06 07:44 UTC, Himani-ja commented
Updating code